name: Build and Push docker image

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@V4.1.1
      -
        name: Set up QEMU
        uses: